export { default as AppMain }from './AppMain'
// export {default as Settings}from './Settings'
// export {default as Sidebar}from './Sidebar/index.vue'
// export {default as TagsView}from './TagsView/index.vue'
export {default as TopView}from './TopBar/TopView.vue'
export {default as PageFooter}from './PageFooter/index.vue'
